create function pg_temp.assert_true(result boolean,label text) returns void language plpgsql as $$
begin if result is distinct from true then raise exception 'FAIL: %',label; end if; end $$;
create function pg_temp.denied(statement text) returns void language plpgsql as $$
begin begin execute statement; exception when insufficient_privilege then return; end; raise exception 'Unexpected access: %',statement; end $$;
begin;
select pg_temp.assert_true((select count(*)=0 from pg_policies where schemaname='public' and (coalesce(qual,'')||coalesce(with_check,'')) like '%auth.uid()%'),'No policies depend on Supabase identity');
select pg_temp.assert_true((select count(*)=0 from pg_constraint where contype='f' and connamespace='public'::regnamespace and confrelid='auth.users'::regclass),'No application FK depends on Supabase users');
select pg_temp.assert_true((select exists(select 1 from private.students where id='99999999-9999-4999-8999-999999999999')),'Legacy UUID preserved');
delete from auth.users where id='99999999-9999-4999-8999-999999999999';
select pg_temp.assert_true((select count(*)=1 from public.notes where user_id='99999999-9999-4999-8999-999999999999'),'Legacy notes now independent of Supabase users');
set local role prepyard_web;
select set_config('test.alice',private.register_google_student('google-alice','alice@example.test','Alice')::text,true);
select set_config('test.bob',private.register_google_student('google-bob','bob@example.test','Bob')::text,true);
select pg_temp.assert_true(private.register_google_student('google-alice','alice-new@example.test','Alice')::text=current_setting('test.alice'),'Changed email retains Google identity');
select pg_temp.assert_true(private.register_google_student('google-other','alice-new@example.test','Other')::text<>current_setting('test.alice'),'Same email never merges Google subjects');
select pg_temp.denied('select * from private.students');
select pg_temp.denied('select * from public.questions');
set local role authenticated;
select pg_temp.denied($test$select private.register_google_student('forged','fake@example.test','Fake')$test$);
select pg_temp.denied('select * from public.sources');
select pg_temp.denied('select * from public.source_snapshots');
select pg_temp.denied('select * from public.import_runs');
select pg_temp.denied('select * from private.students');
select pg_temp.assert_true((select count(*)=0 from public.questions),'No identity cannot read catalogue');
reset role;
set local role service_role;
select pg_temp.assert_true((select exists(select 1 from private.students where id=current_setting('test.alice')::uuid)),'Trusted maintenance role can manage application identities');
update public.sources set reuse_status='approved',enabled=true,is_public=true;
select public.publish_source_snapshot(id) from public.source_snapshots;
reset role;
set local role authenticated;
select set_config('prepyard.student_id',current_setting('test.alice'),true);
select pg_temp.assert_true((select count(*)=1 from public.questions),'Google student reads published question');
select pg_temp.assert_true((select count(company_id)=2 from public.company_question_observations),'Google student reads eligible observations');
select pg_temp.denied('select snapshot_id from public.company_question_observations');
select pg_temp.denied('select source_rank from public.company_question_observations');
insert into public.notes(user_id,question_id,content) select private.student_id(),id,'Alice private note' from public.questions;
insert into public.user_question_state(user_id,question_id,status) select private.student_id(),id,'solved' from public.questions;
insert into public.sheets(owner_id,slug,title) values(private.student_id(),'google-alice','Alice sheet');
insert into public.sheet_items(sheet_id,question_id,position) select s.id,q.id,0 from public.sheets s cross join public.questions q where s.slug='google-alice';
insert into public.practice_events(user_id,question_id,event_type) select private.student_id(),id,'solved' from public.questions;
insert into public.correction_reports(reporter_id,question_id,details) select private.student_id(),id,'Please review association' from public.questions;
select pg_temp.assert_true((select count(*)=1 from public.notes),'Alice reads own notes');
select set_config('prepyard.student_id',current_setting('test.bob'),true);
select pg_temp.assert_true((select count(*)=0 from public.notes),'Bob cannot read Alice notes');
select pg_temp.assert_true((select count(*)=0 from public.user_question_state),'Bob cannot read Alice progress');
select pg_temp.assert_true((select count(*)=0 from public.sheets),'Bob cannot read Alice private sheets');
select pg_temp.assert_true((select count(*)=0 from public.sheet_items),'Bob cannot read Alice private items');
select pg_temp.assert_true((select count(*)=0 from public.practice_events),'Bob cannot read Alice practice');
select pg_temp.assert_true((select count(*)=0 from public.correction_reports),'Bob cannot read Alice reports');
with changed as(update public.notes set content='Hacked' returning 1) select pg_temp.assert_true((select count(*)=0 from changed),'Cross-user update changes no notes');
with removed as(delete from public.user_question_state returning 1) select pg_temp.assert_true((select count(*)=0 from removed),'Cross-user delete changes no progress');
select pg_temp.denied($test$insert into public.notes(user_id,question_id,content) select current_setting('test.alice')::uuid,id,'Forged note' from public.questions$test$);
select set_config('prepyard.student_id',current_setting('test.alice'),true);
select pg_temp.assert_true((select content='Alice private note' from public.notes),'Alice note survived foreign attempts');
reset role;
delete from private.students where id=current_setting('test.alice')::uuid;
select pg_temp.assert_true((select count(*)=0 from public.notes where user_id=current_setting('test.alice')::uuid),'App account deletion cascades owned records');
set local role anon;
select pg_temp.denied('select * from public.questions');
select pg_temp.denied($test$select private.register_google_student('forged','fake@example.test','Fake')$test$);
reset role;
rollback;
-- Confirm transaction-local identity does not leak between pooled operations.
begin;
set local role authenticated;
select pg_temp.assert_true(private.student_id() is null,'Transaction cleared student identity');
select pg_temp.assert_true((select count(*)=0 from public.questions),'Cleared identity denies catalogue');
rollback;
select 'Google identity, legacy preservation, ownership, and transaction isolation checks passed' as result;
