create function pg_temp.assert_true(result boolean,label text) returns void language plpgsql as $$
begin if result is distinct from true then raise exception 'FAIL: %',label; end if; end $$;
create function pg_temp.denied(statement text) returns void language plpgsql as $$
begin begin execute statement; exception when insufficient_privilege then return; end; raise exception 'Unexpected access: %',statement; end $$;
begin;
set local role prepyard_web;
select pg_temp.denied('select * from private.password_accounts');
select pg_temp.denied('select * from private.email_tokens');
select pg_temp.denied('select * from private.auth_limits');
select pg_temp.assert_true(private.auth_attempt('test',2,900),'First attempt allowed');
select pg_temp.assert_true(private.auth_attempt('test',2,900),'Second attempt allowed');
select pg_temp.assert_true(not private.auth_attempt('test',2,900),'Excess attempts denied');
select pg_temp.assert_true(private.issue_email_token('password@example.test','verify','scrypt$'||repeat('a',32)||'$'||repeat('b',128),'Student',repeat('1',64)),'Pending signup');
select pg_temp.assert_true(not exists(select 1 from private.password_identity('password@example.test')),'Unverified cannot log in');
select pg_temp.assert_true(not private.consume_email_token(repeat('1',64),'reset','scrypt$'||repeat('a',32)||'$'||repeat('c',128)),'Token purpose enforced');
select pg_temp.assert_true(private.consume_email_token(repeat('1',64),'verify',null),'Verification creates identity');
select pg_temp.assert_true(not private.consume_email_token(repeat('1',64),'verify',null),'Verification cannot replay');
select pg_temp.assert_true((select count(*)=1 from private.password_identity('password@example.test')),'Verified account can be resolved');
select set_config('test.password_id',(select id::text from private.password_identity('password@example.test')),true);
select pg_temp.assert_true(private.password_session(current_setting('test.password_id')::uuid,1),'New session valid');
select pg_temp.assert_true(not private.issue_email_token('password@example.test','verify','scrypt$'||repeat('a',32)||'$'||repeat('c',128),'Attacker',repeat('2',64)),'Signup cannot replace verified password');
select pg_temp.assert_true(not private.issue_email_token('unknown@example.test','reset',null,'',repeat('2',64)),'Unknown reset creates no token');
select pg_temp.assert_true(private.issue_email_token('password@example.test','reset',null,'',repeat('2',64)),'Reset requested');
select pg_temp.assert_true(private.issue_email_token('password@example.test','reset',null,'',repeat('3',64)),'Reset reissued');
select pg_temp.assert_true(not private.consume_email_token(repeat('2',64),'reset','scrypt$'||repeat('a',32)||'$'||repeat('c',128)),'Older reset invalidated');
select pg_temp.assert_true(private.consume_email_token(repeat('3',64),'reset','scrypt$'||repeat('a',32)||'$'||repeat('c',128)),'Reset consumed');
select pg_temp.assert_true(not private.consume_email_token(repeat('3',64),'reset','scrypt$'||repeat('a',32)||'$'||repeat('c',128)),'Reset cannot replay');
select pg_temp.assert_true(not private.password_session(current_setting('test.password_id')::uuid,1),'Old sessions revoked');
select pg_temp.assert_true(private.password_session(current_setting('test.password_id')::uuid,2),'New version valid');
select pg_temp.assert_true((select password_hash='scrypt$'||repeat('a',32)||'$'||repeat('c',128) from private.password_identity('password@example.test')),'Password replaced');
select pg_temp.assert_true(private.register_google_student('password-separate','password@example.test','Google Student')<>current_setting('test.password_id')::uuid,'No automatic Google linking');
select private.issue_email_token('expired@example.test','verify','scrypt$'||repeat('a',32)||'$'||repeat('b',128),'Expired',repeat('4',64));
select private.issue_email_token('password@example.test','reset',null,'',repeat('5',64));
reset role;
update private.email_tokens set expires_at=now()-interval '1 second';
update private.auth_limits set started_at=now()-interval '1 hour' where key='test';
set local role prepyard_web;
select pg_temp.assert_true(not private.consume_email_token(repeat('4',64),'verify',null),'Expired verification denied');
select pg_temp.assert_true(not private.consume_email_token(repeat('5',64),'reset','scrypt$'||repeat('a',32)||'$'||repeat('d',128)),'Expired reset denied');
select pg_temp.assert_true(private.auth_attempt('test',2,900),'Rate window recovers');
set local role authenticated;
select pg_temp.denied('select * from private.password_accounts');
select pg_temp.denied($q$select * from private.password_identity('password@example.test')$q$);
select pg_temp.denied($q$select private.consume_email_token(repeat('1',64),'verify',null)$q$);
reset role;
set local role service_role;
update public.sources set reuse_status='approved',enabled=true,is_public=true;
select public.publish_source_snapshot(id) from public.source_snapshots;
set local role authenticated;
select set_config('prepyard.student_id',current_setting('test.password_id'),true);
insert into public.notes(user_id,question_id,content) select private.student_id(),id,'Password account private note' from public.questions limit 1;
select pg_temp.assert_true((select count(*)=1 from public.notes),'Password account owns its notes');
select set_config('prepyard.student_id','11111111-1111-4111-8111-111111111111',true);
select pg_temp.assert_true((select count(*)=0 from public.notes),'Another account cannot read password-account notes');
set local role anon;
select pg_temp.denied('select * from private.email_tokens');
select pg_temp.denied($q$select * from private.password_identity('password@example.test')$q$);
rollback;
