// Emits the company directory as a reviewable Markdown file, and marks which
// companies have vendored artwork. Run from the repository root.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const snapshot = JSON.parse(
  readFileSync("artifacts/imports/repository/snapshot.json", "utf8"),
);
const companies = snapshot.companies;
const hasMark = (slug) => existsSync(`assets/company-logos/${slug}.svg`);

const counts = companies.reduce((acc, c) => {
  const letter = /^[0-9]/.test(c.name) ? "0-9" : c.name[0].toUpperCase();
  acc[letter] ??= [];
  acc[letter].push(c);
  return acc;
}, {});
const letters = Object.keys(counts).sort((a, b) => {
  if (a === "0-9") return -1;
  if (b === "0-9") return 1;
  return a.localeCompare(b);
});

const marked = companies.filter((c) => hasMark(c.slug)).length;
let out = `# Company directory\n\n`;
out += `All ${companies.length} companies in the catalogue, from the pinned import of\n`;
out += `\`cs-satyam/leetcode-companywise-questions\` at revision\n`;
out += `\`${snapshot.revision}\`.\n\n`;
out += `Generated by \`scripts/company-list.mjs\` from the import snapshot. Do not edit by hand.\n\n`;
out += `A **bold** name has original artwork vendored in \`assets/company-logos/\` (${marked} of ${companies.length}).\n\n`;
// Prettier reformats markdown tables, so emit one it will leave alone rather than
// letting `prettier --check` flag a freshly generated file.
const stats = [
  ["Total companies", companies.length],
  ["With a brand mark", marked],
  ["Monogram only", companies.length - marked],
  ["Distinct questions", snapshot.questions.length],
  ["Company/window observations", snapshot.observations.length],
];
const labelWidth = Math.max(...stats.map(([label]) => label.length));
const countWidth = Math.max(
  "Count".length,
  ...stats.map(([, value]) => String(value).length),
);
out += `| ${"Statistic".padEnd(labelWidth)} | ${"Count".padEnd(countWidth)} |\n`;
out += `| ${"-".repeat(labelWidth)} | ${"-".repeat(countWidth)} |\n`;
for (const [label, value] of stats)
  out += `| ${label.padEnd(labelWidth)} | ${String(value).padEnd(countWidth)} |\n`;
out += "\n";

for (const letter of letters) {
  const list = counts[letter];
  const withMark = list.filter((c) => hasMark(c.slug)).length;
  out += `## ${letter} (${list.length})\n\n`;
  out += `With artwork: ${withMark}. Without: ${list.length - withMark}.\n\n`;
  for (const company of list)
    out += `- ${hasMark(company.slug) ? "**" : ""}${company.name}${
      hasMark(company.slug) ? "**" : ""
    } \`${company.slug}\`\n`;
  out += "\n";
}
// Each section ends with a blank line, which leaves a trailing one; prettier strips
// that, so trim here rather than let `format:check` flag a fresh file.
writeFileSync("docs/company-list.md", out.trimEnd() + "\n");
console.log(
  `Wrote docs/company-list.md: ${companies.length} companies, ${marked} with artwork.`,
);
